source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-static-assets'
gem 'rest-client'
gem 'haml'
gem 'puma'
gem 'prometheus-client'
gem 'rspec-core'
gem 'test-unit'

group :development do
  gem 'rubocop'
end
