node('docker') {
withCredentials([usernamePassword(credentialsId: 'docker_registry',
  passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USER')]) {

def id = "${env.BUILD_ID}"
def staging_docker = "35.156.40.16"
def git_repo = env.GIT_REPO_URL

  stage 'Checkout'
    checkout scm

  stage 'Package Image'
    //Packaging the image into a Docker image
    def pkg = docker.build ("${env.DOCKERHUB_USER}/blog_ui", 'app/blog_ui')

  //Допишем stage с тестами после этого комментария
  stage 'Run tests'
    pkg.inside {
      sh 'rspec app/blog_ui/tests.rb'
  }

  stage 'Push Image to DockerHub'
    //Pushing the packaged app in image into DockerHub
    docker.withRegistry ('https://index.docker.io/v1/', 'docker_registry') {
      pkg.push "${id}"
      pkg.push 'latest'
  }

  //Дописываем stage с деплоем сразу после комментария
  stage 'Deploy to staging'
    sh "DOCKER_CERT_PATH='/.docker' docker-compose -H ${staging_docker}:2376 -f app/docker-compose.yml pull blog_ui"
    sh "DOCKER_CERT_PATH='/.docker' docker-compose -H ${staging_docker}:2376 -f app/docker-compose.yml up -d blog_ui"

  }
}
