version: '2'

services:
  jenkins-master:
    build: infrastructure/jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkins-slave:
    restart: always
    build: infrastructure/jenkins-slave
    privileged: true
    volumes:
      - jenkins_slave_home:/var/jenkins_home
    environment:
      - JENKINS_URL=http://jenkins-master:8080 a7621c7f283712d48842552ad68c139f10d27c47c93c15005d75366f529bd330 slave1
volumes:
  jenkins_home:
    driver: local
  jenkins_slave_home:
    driver: local
