node('docker') {
withCredentials([usernamePassword(credentialsId: 'docker_registry',
  passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USER')]) {

def staging_docker = "<docker-machine-mk ip>"
def git_repo = env.GIT_REPO_URL

stage 'Checkout'
    checkout scm

stage 'Package Image'
    //Packaging the image into a Docker image
    def pkg = docker.build ("${env.DOCKERHUB_USER}/ruby", 'app/ruby')

stage 'Push Image to DockerHub'
    //Pushing the packaged app in image into DockerHub
    docker.withRegistry ('https://index.docker.io/v1/', 'docker_registry') {
        pkg.push '2.3'
        pkg.push 'latest'
    }

}
}
