node ('docker') {
withCredentials([usernamePassword(credentialsId: 'docker_registry',
  passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USER')]) {
                println(env.DOCKERHUB_USER)

def staging_docker = "35.156.40.16"
def git_repo = env.GIT_REPO_URL

stage 'Checkout'
  checkout scm

stage 'Build Image'
  //Packaging the image into a Docker image
  def pkg = docker.build ("${env.DOCKERHUB_USER}/mongodb", 'app/mongodb')

//Допишем stage с тестами после этого комментария
stage('Infra tests')
  pkg.inside {
    sh 'mongod --version | grep "db version" | grep 3.2.6'
}

stage 'Push Image to DockerHub'
    //Pushing the packaged app in image into DockerHub
    docker.withRegistry ('https://index.docker.io/v1/', 'docker_registry') {
      pkg.push '3.2.6'
      pkg.push 'latest'
    }

//Дописываем stage с деплоем сразу после комментария

}
}
